name: cv_portfolio_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # --- YOUR PACKAGES ---
  url_launcher: ^6.2.5
  pdf: ^3.10.4
  printing: ^5.12.0
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.7+1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ✅ ADDED FOR ICON GENERATION
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # ✅ Make sure 'profile.png' and 'icon.png' exist in assets folder
  assets:
    - assets/profile.png
    # - assets/icon.png (Optional: Agar app ke andar bhi use karna ho)

# ✅ ICON CONFIGURATION (Sabse Important)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png" # Make sure ye image assets folder mein ho!
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"